import { money } from '@/lib/format'

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
export const monthName = (m: number) => MONTHS[m - 1] ?? String(m)

const esc = (s: unknown) => String(s ?? '').replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string))

/** Opens a clean payslip in a new window and starts printing (the browser can also save it as PDF). */
export function printPayslip(line: any, orgName: string) {
  const items: any[] = Array.isArray(line.details) ? line.details : []
  const allowances = items.filter(i => i.kind === 'allowance')
  const deductions = items.filter(i => i.kind === 'deduction')
  const cur = line.currency_code || 'TZS'
  const row = (label: string, amount: number, bold = false) =>
    `<tr${bold ? ' class="b"' : ''}><td>${esc(label)}</td><td class="n">${money(amount, '')}</td></tr>`

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Payslip ${esc(line.employee_name)} ${monthName(line.period_month)} ${line.period_year}</title>
<style>
 body{font-family:Arial,Helvetica,sans-serif;color:#102a2b;margin:32px;max-width:720px}
 h1{margin:0;font-size:22px;color:#087f82} h2{font-size:14px;margin:22px 0 6px;border-bottom:1px solid #cfd8d8;padding-bottom:4px}
 .muted{color:#5d7478;font-size:12px} table{width:100%;border-collapse:collapse;font-size:13px} td{padding:5px 2px} .n{text-align:right}
 .b td{font-weight:700;border-top:1px solid #cfd8d8} .net{font-size:16px;background:#eef7f6} .grid{display:flex;justify-content:space-between;gap:20px}
 @media print{body{margin:12mm}}
</style></head><body>
<div class="grid"><div><h1>${esc(orgName)}</h1><div class="muted">Payslip for ${monthName(line.period_month)} ${line.period_year}</div></div>
<div class="muted" style="text-align:right">Currency: ${esc(cur)}</div></div>
<h2>Employee</h2>
<div>${esc(line.employee_name)} <span class="muted">(${esc(line.employee_no)})</span></div>
<div class="muted">${esc(line.position || '')}${line.position && line.department ? ' · ' : ''}${esc(line.department || '')}</div>
<h2>Earnings</h2><table>
${row('Basic salary', line.basic_salary)}
${allowances.map(a => row(a.name + (a.taxable ? '' : ' (not taxed)'), a.amount)).join('')}
${row('Gross pay', line.gross_pay, true)}</table>
<h2>Deductions</h2><table>
${row('NSSF (employee)', line.nssf_employee)}
${row('PAYE (income tax)', line.paye)}
${Number(line.nhif_employee) > 0 ? row('NHIF (employee)', line.nhif_employee) : ''}
${deductions.map(d => row(d.name, d.amount)).join('')}
${row('Total deductions', Number(line.nssf_employee) + Number(line.paye) + Number(line.nhif_employee) + Number(line.other_deductions), true)}</table>
<table style="margin-top:14px"><tr class="b net"><td>NET PAY</td><td class="n">${money(line.net_pay, cur)}</td></tr></table>
<p class="muted" style="margin-top:28px">This payslip was generated by the Terraviva HR System.</p>
<script>window.onload=function(){window.print()}</script></body></html>`

  const w = window.open('', '_blank')
  if (!w) { window.alert('Please allow pop-ups for this site to print the payslip.'); return }
  w.document.open(); w.document.write(html); w.document.close()
}
